name: da_ka
description: A new Flutter project.
version: 1.0.0+1

environment:
  sdk: ">=2.2.2 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
  syncfusion_localizations: ^18.3.42
  url_launcher: ^5.7.8
  simple_splashscreen: ^0.1.3
  full_screen_image: 1.0.2
  flutter_screenutil: ^3.2.0
  path_provider: ^1.6.22
  sqflite: ^1.3.1
  permission_handler: ^5.0.1+1
  flustars: ^0.3.2
  nav_router: ^0.0.6
  common_utils: ^1.2.1
  share_extend: ^1.1.9
  photo_view: ^0.9.2
  flutter_webview_plugin: ^0.3.11
  webview_flutter: ^1.0.5
  # webview_flutter: ^0.3.21
  flutter_tts: ^1.3.0
  flutter_slidable: ^0.5.5
  flutter_picker: ^1.1.5
  flutter_material_pickers: 1.8.1
  settings_ui: ^0.4.0
  archive: ^2.0.13
  timeline_tile: ^0.1.2
  filesize: ^1.0.4
  wakelock: ^0.1.4+2
  scroll_to_index: ^1.0.6
  oktoast: ^2.1.7
  sticky_and_expandable_list: ^0.2.3
  dynamic_theme: ^1.0.0
  flutter_svg: ^0.19.1
  pdf_text: ^0.3.1
  syncfusion_flutter_pdfviewer: ^18.3.42-beta

dev_dependencies:
  flutter_test:
    sdk: flutter
  pedantic: ^1.9.0
  flutter_launcher_icons: "^0.7.3"

flutter_icons:
  android: "launcher_icon"
  ios: true
  image_path: "assets/icon/icon.png"
# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec

# The following section is specific to Flutter.
flutter:
  # The following line ensures that the Material Icons font is
  # included with your application, so that you can use the icons in
  # the material Icons class.
  uses-material-design: true
  # To add assets to your application, add an assets section, like this:
  assets:
    - assets/db/clock_in.db
    - assets/db/bible.db
    - assets/db/lifestudy.db
    - assets/db/nee.db
    - assets/db/help.zip
    - assets/icon/icon.png
    - assets/icon/isilo.png
    - assets/icon/dict.svg
    - assets/icon/pdf.svg
    - assets/icon/book_old.svg
    - assets/icon/book_new.svg
    - assets/icon/life_reading.svg
    - assets/icon/kuaichuan.svg
    - assets/icon/word.svg
    - assets/icon/bundle.svg
    - assets/apk/isilo.apk
    - assets/apk/fastTransport.apk
    - assets/pf0

  fonts:
    - family: Raleway
      fonts:
        - asset: assets/fonts/raleway/Raleway-Regular.ttf
        - asset: assets/fonts/raleway/Raleway-Medium.ttf
          weight: 500
        - asset: assets/fonts/raleway/Raleway-SemiBold.ttf
          weight: 600

    - family: OpenSans
      fonts:
        - asset: assets/fonts/cobsg/OpenSans-Regular.ttf
          weight: 500
    - family: kaiti
      fonts:
        - asset: assets/fonts/kaiti/simkai.ttf
