name: da_ka
description: A new Flutter project.

# The following defines the version and build number for your application.
# A version number is three numbers separated by dots, like 1.2.43
# followed by an optional build number separated by a +.
# Both the version and the builder number may be overridden in flutter
# build by specifying --build-name and --build-number, respectively.
# In Android, build-name is used as versionName while build-number used as versionCode.
# Read more about Android versioning at https://developer.android.com/studio/publish/versioning
# In iOS, build-name is used as CFBundleShortVersionString while build-number used as CFBundleVersion.
# Read more about iOS versioning at
# https://developer.apple.com/library/archive/documentation/General/Reference/InfoPlistKeyReference/Articles/CoreFoundationKeys.html
version: 1.0.0+1

environment:
  sdk: ">=2.2.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  # The following adds the Cupertino Icons font to your application.
  # Use with the CupertinoIcons class for iOS style icons.
  cupertino_icons: ^0.1.2
  simple_splashscreen: ^0.1.3
  full_screen_image: 1.0.2
  flutter_screenutil: ^2.3.0
  path_provider: ^1.6.11
  sqflite: ^1.3.1
  permission_handler: ^5.0.1+1
  flustars: ^0.3.2
  nav_router: ^0.0.6
  status_alert: ^0.1.2
  common_utils: ^1.2.1
  flutter_full_pdf_viewer: ^1.0.6
  share_extend: ^1.1.9
  photo_view: ^0.9.2
  webview_flutter: ^0.3.22+1
  search_widget: ^1.0.2
  flutter_tts: ^1.2.6
  flutter_slidable: ^0.5.5
  fluttertoast: ^7.0.2
  flutter_picker: ^1.1.5
  qr_flutter: ^3.2.0
  # qr_code_scanner: ^0.0.13
  flutter_qr_bar_scanner: ^1.0.2
  connectivity: ^0.4.9+2
  flutter_p2p: ^0.1.1

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_launcher_icons: "^0.7.3"

flutter_icons:
  android: "launcher_icon"
  ios: true
  image_path: "assets/icon/icon.png"
# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec

# The following section is specific to Flutter.
flutter:
  # The following line ensures that the Material Icons font is
  # included with your application, so that you can use the icons in
  # the material Icons class.
  uses-material-design: true
  # To add assets to your application, add an assets section, like this:
  assets:
    - assets/images/7.png
    - assets/db/clock_in.db
    - assets/icon/icon.png
    - assets/icon/isilo.png
    - assets/apk/isilo.apk

  fonts:
    - family: Raleway
      fonts:
        - asset: assets/fonts/raleway/Raleway-Regular.ttf
        - asset: assets/fonts/raleway/Raleway-Medium.ttf
          weight: 500
        - asset: assets/fonts/raleway/Raleway-SemiBold.ttf
          weight: 600

    - family: kaiti
      fonts:
        - asset: assets/fonts/kaiti/simkai.ttf
